# Generated by Django 4.0.4 on 2022-05-18 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_tracks_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlists',
            name='user',
        ),
        migrations.AddField(
            model_name='playlists',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
