# Generated by Django 4.0.4 on 2022-05-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_remove_playlists_user_playlists_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='cover',
            field=models.ImageField(default=None, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='charts',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
