# Generated by Django 4.0.4 on 2022-05-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_tracks_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='cover',
            field=models.ImageField(default='https://i.pinimg.com/564x/63/77/b9/6377b973d63f875455b450361e6c13fd.jpg', null=True, upload_to='covers/'),
        ),
    ]
