# Generated by Django 4.0.4 on 2022-05-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_alter_tracks_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='genres',
        ),
    ]
